/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flottevehicules;

import flottevehicules.vue.Menu;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        new Menu();
    }
}
