/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flottevehicules;

import flottevehicules.vue.Menu;

public class App {
    public static void main(String[] args) {
        new Menu();
    }
}
